# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - script: mvn install
- stage: Test
  jobs:
  - job: Tests
    steps:
    - script: mvn test

- stage: Deploy
  jobs:
  - job: Deploy
    steps:
    - script: echo Deploying the code!